### ISSUE TITLE
Doc issue -- Any relation to json-schema.org?

### ISSUE THREAD

**Issue by seagreen** [silkapp/json-schema#20]
Is this a totally separate project from http://json-schema.org/? If so should I make a documentation PR to clarify that? The similarity of the two projects' names and purposes is confusing.

**Comment by bergmark** [comment]
Yeah, the name clash is coincidental, it might even be that we named it before json-schema.org existed :)

I'd appreciate a PR for this!

**Comment by seagreen** [comment]
Sounds good.

https://github.com/silkapp/json-schema/pulls
