### ISSUE TITLE
Arbitrary predicates

### ISSUE THREAD

**Issue by mitchellwrosen** [silkapp/json-schema#23]
Hi, I just came across this package and I'm curious, is there any reason why schemas don't contain arbitrary predicates to run over the data? 

For example, it looks like the only thing you can check on a string value is its length:

```haskell
data Schema =
  ...
  | Value LengthBound
```

Why not this?

```haskell
data Schema =
  ...
  | Value (Text -> Bool)
```

Thanks!

**Comment by hesselink** [comment]
Hi @mitchellwrosen, the reason is that we use the schemas for documentation generation. This could work with arbitrary functions by describing them manually, but since we never needed the flexibility, currently arbitrary predicates don't exist. Can you tell me more about your use case?

**Comment by mitchellwrosen** [comment]
I see. No problem - I whipped up https://github.com/mitchellwrosen/json-validation in the meantime last night ([haddocks](https://mitchellwrosen.github.io/json-validation/json-validation-0.1.0.0/Data-Aeson-Validation.html)). It's significantly lower-tech than this library but does what I need it to (for now).

My use case is comparing to an exact string in some unit tests; I realize now that there is a `Constant` constructor but I didn't notice it before!
